execute pathogen#infect()

set wildmode=longest,list
set tabstop=4
set smartindent
set number
set statusline=%<\ %f\ %r\ %=%l\ of\ %L\ 
set sw=4
set clipboard=unnamed
set backspace=2
set backspace=indent,eol,start
set showcmd
colorscheme gruvbox
syntax on
filetype plugin on

" split navigating
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>


set completeopt-=preview

let g:ycm_key_list_select_completion=[]
let g:ycm_key_list_previous_completion=[]

if !exists("g:ycm_semantic_triggers")
	let g:ycm_semantic_triggers = {}
	endif
	let g:ycm_semantic_triggers["typescript"] = ["."]


let g:typescript_compiler_binary = 'tsc'
let g:typescript_compiler_options = ''
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

autocmd FileType typescript JsPreTmpl html
autocmd FileType typescript syn clear foldBraces

let g:jsx_ext_required = 0

set runtimepath^=~/.vim/bundle/ctrlp.vim

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_aggregate_errors = 1
let g:syntastic_javascript_checkers = ["eslint", "tsuquyomi"]
let g:tsuquyomi_disable_quickfix = 1

let g:AutoPairsUseInsertedCount = 1

" status line styling
hi StatusLineNC ctermbg=bg ctermfg=white cterm=NONE
hi StatusLine ctermbg=bg ctermfg=1 cterm=NONE

" split window styling
set fillchars+=vert:\ 
hi LineNr ctermbg=bg
set foldcolumn=2
hi foldcolumn ctermbg=bg
hi VertSplit ctermbg=bg ctermfg=bg

